AWSTemplateFormatVersion : 2010-09-09

Resources:
  ExampleBucket:
    Type: AWS::S3::Bucket

  ExampleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: panda-1-demo            #IAM Role Policy Name
          PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:                         #Permission Services of AWS Through IAM
                - s3:GetObject
                - s3:ListObject
              Resource: !Sub *                #S3 Bucket Name (arn link from s3 bucket, Paste Here)
